# -*- coding: utf-8 -*-
"""PII.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a7dsDv9EBeaVV9X_37ZqVMPuqiBSUAod
"""

ls

cd pipeline/manifests/

ls

pip install gliner

from gliner import GLiNER

model = GLiNER.from_pretrained("knowledgator/gliner-pii-large-v1.0")

model = GLiNER.from_pretrained(
    "knowledgator/gliner-pii-large-v1.0",
    device="cuda"
)



print(model.device)

text = "John Smith called from 415-555-1234. His email is john@gmail.com"

labels = [
    "name",
    "phone number",
    "email address"
]

entities = model.predict_entities(text, labels, threshold=0.3)

for e in entities:
    print(e)

import html
import pandas as pd
from gliner import GLiNER
from IPython.display import display, HTML

# -----------------------------
# Load CSV
# -----------------------------
df = pd.read_csv("final_df.csv")

# -----------------------------
# Load model
# -----------------------------
model = GLiNER.from_pretrained("knowledgator/gliner-pii-large-v1.0")

# -----------------------------
# Labels
# Use natural label names, not snake_case
# -----------------------------
labels = [
    "person name",
    "age",
    "location",
    "date",
    "phone number",
    "aadhaar number",
    "medical condition",
    "lab result",
    "medication",
    "email address",
    "insurance id",
    "doctor name",
    "institution name"
]

# -----------------------------
# Colors for highlight background
# -----------------------------
LABEL_STYLES = {
    "person name":      {"bg": "#ffd6d6", "border": "#ef4444"},
    "age":              {"bg": "#dcfce7", "border": "#22c55e"},
    "location":         {"bg": "#dbeafe", "border": "#3b82f6"},
    "date":             {"bg": "#fef3c7", "border": "#eab308"},
    "phone number":     {"bg": "#ede9fe", "border": "#8b5cf6"},
    "aadhaar number":   {"bg": "#ccfbf1", "border": "#14b8a6"},
    "medical condition":{"bg": "#fed7aa", "border": "#f97316"},
    "lab result":       {"bg": "#cffafe", "border": "#06b6d4"},
    "medication":       {"bg": "#ecfccb", "border": "#84cc16"},
    "email address":    {"bg": "#fbcfe8", "border": "#ec4899"},
    "insurance id":     {"bg": "#fecdd3", "border": "#f43f5e"},
    "doctor name":      {"bg": "#d1fae5", "border": "#10b981"},
    "institution name":  {"bg": "#dbeafe", "border": "#3b82f6"},
}

DEFAULT_STYLE = {"bg": "#e5e7eb", "border": "#6b7280"}


# -----------------------------
# Resolve overlaps
# Keeps highest-score span when overlaps happen
# -----------------------------
def resolve_overlaps(entities):
    entities = sorted(
        entities,
        key=lambda x: (x["start"], -(x["end"] - x["start"]), -x["score"])
    )

    kept = []
    for ent in entities:
        has_overlap = False
        replace_idx = None

        for i, k in enumerate(kept):
            overlap = not (ent["end"] <= k["start"] or ent["start"] >= k["end"])
            if overlap:
                has_overlap = True
                if ent["score"] > k["score"]:
                    replace_idx = i
                break

        if not has_overlap:
            kept.append(ent)
        elif replace_idx is not None:
            kept[replace_idx] = ent

    kept = sorted(kept, key=lambda x: x["start"])
    return kept


# -----------------------------
# Get transcript + pii entities for one row
# -----------------------------
def get_row_pii(idx, text_col="final_transcript.1", threshold=0.35):
    if idx < 0 or idx >= len(df):
        raise IndexError(f"Index {idx} out of range. Valid: 0 to {len(df)-1}")

    if text_col not in df.columns:
        raise KeyError(f"Column '{text_col}' not found")

    text = df.loc[idx, text_col]

    if pd.isna(text) or not str(text).strip():
        raise ValueError(f"Empty text at row {idx}")

    text = str(text)

    raw_entities = model.predict_entities(text, labels, threshold=threshold)

    entities = []
    for e in raw_entities:
        entities.append({
            "text": e["text"],
            "label": e["label"],
            "start": int(e["start"]),
            "end": int(e["end"]),
            "score": float(e.get("score", 0.0)),
        })

    entities = resolve_overlaps(entities)
    return text, entities


# -----------------------------
# Inline text highlight renderer
# Like your screenshot
# -----------------------------
def render_inline_highlighted_text(text, entities, show_label=False):
    out = []
    cursor = 0

    for ent in entities:
        start = ent["start"]
        end = ent["end"]
        label = ent["label"]

        style = LABEL_STYLES.get(label, DEFAULT_STYLE)

        # normal text before entity
        if cursor < start:
            out.append(html.escape(text[cursor:start]))

        span_text = html.escape(text[start:end])

        if show_label:
            out.append(
                f"""<span style="
                    background:{style['bg']};
                    border:1px solid {style['border']};
                    border-radius:4px;
                    padding:1px 3px;
                    margin:0 1px;
                    display:inline-block;
                ">{span_text}<span style="
                    font-size:10px;
                    font-weight:bold;
                    margin-left:4px;
                    color:#111827;
                ">[{html.escape(label)}]</span></span>"""
            )
        else:
            out.append(
                f"""<span style="
                    background:{style['bg']};
                    border-radius:3px;
                    padding:1px 2px;
                ">{span_text}</span>"""
            )

        cursor = end

    # remaining text
    if cursor < len(text):
        out.append(html.escape(text[cursor:]))

    return f"""
    <div style="
        background:#ffffff;
        color:#111827;
        border:1px solid #d1d5db;
        border-radius:8px;
        padding:14px 16px;
        line-height:1.9;
        font-size:20px;
        white-space:pre-wrap;
        word-wrap:break-word;
    ">
        {''.join(out)}
    </div>
    """


# -----------------------------
# Main display function
# -----------------------------
def show_pii_inline(idx, text_col="final_transcript.1", threshold=0.35, show_label=False):
    text, entities = get_row_pii(idx, text_col=text_col, threshold=threshold)

    print(f"Row index: {idx}")
    print(f"Detected entities: {len(entities)}")

    html_block = render_inline_highlighted_text(text, entities, show_label=show_label)
    display(HTML(html_block))

    if entities:
        display(pd.DataFrame(entities))

    return text, entities

show_pii_inline(idx=5, text_col="final_transcript.1", threshold=0.35, show_label=True)

show_pii_inline(idx=27, text_col="final_transcript.1", threshold=0.20, show_label=True)

show_pii_inline(idx=100, text_col="final_transcript.1", threshold=0.30, show_label=True)

import html
import pandas as pd
from gliner import GLiNER
from IPython.display import display, HTML

# -----------------------------
# Load CSV
# -----------------------------
df = pd.read_csv("final_df.csv")

# -----------------------------
# Load model
# -----------------------------
model = GLiNER.from_pretrained("knowledgator/gliner-pii-large-v1.0")

# -----------------------------
# Label groups
# -----------------------------
personal_labels = [
    "name",
    "first name",
    "last name",
    "name medical professional",
    "dob",
    "age",
    "gender",
    "marital status",
]

contact_labels = [
    "email address",
    "phone number",
    "ip address",
    "url",
    "location address",
    "location street",
    "location city",
    "location state",
    "location country",
    "location zip",
]

financial_labels = [
    "account number",
    "bank account",
    "routing number",
    "credit card",
    "credit card expiration",
    "cvv",
    "ssn",
    "money",
]

healthcare_labels = [
    "condition",
    "medical process",
    "drug",
    "dose",
    "blood type",
    "injury",
    "organization medical facility",
    "healthcare number",
    "medical code",
]

id_labels = [
    "passport number",
    "driver license",
    "username",
    "password",
    "vehicle id",
]

# Final combined labels
labels = list(dict.fromkeys(
    personal_labels
    + contact_labels
    + financial_labels
    + healthcare_labels
    + id_labels
))

print("Total labels:", len(labels))
print(labels)

# -----------------------------
# Highlight styles
# -----------------------------
LABEL_STYLES = {
    "name": {"bg": "#d1fae5", "border": "#10b981"},
    "first name": {"bg": "#dcfce7", "border": "#22c55e"},
    "last name": {"bg": "#bbf7d0", "border": "#16a34a"},
    "name medical professional": {"bg": "#a7f3d0", "border": "#059669"},
    "dob": {"bg": "#fef3c7", "border": "#eab308"},
    "age": {"bg": "#fde68a", "border": "#d97706"},
    "gender": {"bg": "#fce7f3", "border": "#ec4899"},
    "marital status": {"bg": "#fbcfe8", "border": "#db2777"},

    "email address": {"bg": "#fbcfe8", "border": "#ec4899"},
    "phone number": {"bg": "#ddd6fe", "border": "#8b5cf6"},
    "ip address": {"bg": "#e0e7ff", "border": "#6366f1"},
    "url": {"bg": "#dbeafe", "border": "#3b82f6"},
    "location address": {"bg": "#fee2e2", "border": "#ef4444"},
    "location street": {"bg": "#fecaca", "border": "#dc2626"},
    "location city": {"bg": "#dbeafe", "border": "#2563eb"},
    "location state": {"bg": "#bfdbfe", "border": "#1d4ed8"},
    "location country": {"bg": "#93c5fd", "border": "#1e40af"},
    "location zip": {"bg": "#bae6fd", "border": "#0284c7"},

    "account number": {"bg": "#fef9c3", "border": "#ca8a04"},
    "bank account": {"bg": "#fef08a", "border": "#a16207"},
    "routing number": {"bg": "#fde68a", "border": "#b45309"},
    "credit card": {"bg": "#fed7aa", "border": "#ea580c"},
    "credit card expiration": {"bg": "#fdba74", "border": "#c2410c"},
    "cvv": {"bg": "#fecdd3", "border": "#e11d48"},
    "ssn": {"bg": "#fda4af", "border": "#be123c"},
    "money": {"bg": "#dcfce7", "border": "#15803d"},

    "condition": {"bg": "#fecaca", "border": "#dc2626"},
    "medical process": {"bg": "#fed7aa", "border": "#f97316"},
    "drug": {"bg": "#d9f99d", "border": "#65a30d"},
    "dose": {"bg": "#bef264", "border": "#4d7c0f"},
    "blood type": {"bg": "#fca5a5", "border": "#b91c1c"},
    "injury": {"bg": "#fda4af", "border": "#e11d48"},
    "organization medical facility": {"bg": "#ccfbf1", "border": "#0f766e"},
    "healthcare number": {"bg": "#99f6e4", "border": "#0d9488"},
    "medical code": {"bg": "#a5f3fc", "border": "#0891b2"},

    "passport number": {"bg": "#e9d5ff", "border": "#7c3aed"},
    "driver license": {"bg": "#ddd6fe", "border": "#6d28d9"},
    "username": {"bg": "#e0f2fe", "border": "#0284c7"},
    "password": {"bg": "#fecdd3", "border": "#be123c"},
    "vehicle id": {"bg": "#ede9fe", "border": "#7c3aed"},
}

DEFAULT_STYLE = {"bg": "#e5e7eb", "border": "#6b7280"}

# -----------------------------
# Overlap resolution
# -----------------------------
def resolve_overlaps(entities):
    entities = sorted(
        entities,
        key=lambda x: (x["start"], -(x["end"] - x["start"]), -x["score"])
    )

    kept = []
    for ent in entities:
        overlapping_indices = []

        for i, k in enumerate(kept):
            overlap = not (ent["end"] <= k["start"] or ent["start"] >= k["end"])
            if overlap:
                overlapping_indices.append(i)

        if not overlapping_indices:
            kept.append(ent)
            continue

        # Keep highest score entity among overlapping ones
        best = ent
        replace_indices = []
        for i in overlapping_indices:
            if kept[i]["score"] > best["score"]:
                best = kept[i]
            replace_indices.append(i)

        for i in sorted(replace_indices, reverse=True):
            kept.pop(i)

        kept.append(best)

    kept = sorted(kept, key=lambda x: x["start"])
    return kept

# -----------------------------
# Get entities for one row
# -----------------------------
def get_row_pii(idx, text_col="final_transcript.1", threshold=0.30):
    if idx < 0 or idx >= len(df):
        raise IndexError(f"Index {idx} out of range. Valid: 0 to {len(df)-1}")

    if text_col not in df.columns:
        raise KeyError(f"Column '{text_col}' not found")

    text = df.loc[idx, text_col]

    if pd.isna(text) or not str(text).strip():
        raise ValueError(f"Empty text at row {idx}")

    text = str(text)

    raw_entities = model.predict_entities(text, labels, threshold=threshold)

    entities = []
    for e in raw_entities:
        entities.append({
            "text": e["text"],
            "label": e["label"],
            "start": int(e["start"]),
            "end": int(e["end"]),
            "score": float(e.get("score", 0.0)),
        })

    entities = resolve_overlaps(entities)
    return text, entities

# -----------------------------
# Render inline highlights
# -----------------------------
def render_inline_highlighted_text(text, entities, show_label=False):
    out = []
    cursor = 0

    for ent in entities:
        start = ent["start"]
        end = ent["end"]
        label = ent["label"]

        style = LABEL_STYLES.get(label, DEFAULT_STYLE)

        if cursor < start:
            out.append(html.escape(text[cursor:start]))

        span_text = html.escape(text[start:end])

        if show_label:
            out.append(
                f"""<span style="
                    background:{style['bg']};
                    border:1px solid {style['border']};
                    border-radius:4px;
                    padding:1px 3px;
                    margin:0 1px;
                    display:inline-block;
                ">{span_text}<span style="
                    font-size:10px;
                    font-weight:bold;
                    margin-left:4px;
                    color:#111827;
                ">[{html.escape(label)}]</span></span>"""
            )
        else:
            out.append(
                f"""<span style="
                    background:{style['bg']};
                    border-radius:3px;
                    padding:1px 2px;
                ">{span_text}</span>"""
            )

        cursor = end

    if cursor < len(text):
        out.append(html.escape(text[cursor:]))

    return f"""
    <div style="
        background:#ffffff;
        color:#111827;
        border:1px solid #d1d5db;
        border-radius:8px;
        padding:14px 16px;
        line-height:1.9;
        font-size:20px;
        white-space:pre-wrap;
        word-wrap:break-word;
    ">
        {''.join(out)}
    </div>
    """

# -----------------------------
# Main display function
# -----------------------------
def show_pii_inline(idx, text_col="final_transcript.1", threshold=0.30, show_label=False):
    text, entities = get_row_pii(idx, text_col=text_col, threshold=threshold)

    print(f"Row index: {idx}")
    print(f"Detected entities: {len(entities)}")

    html_block = render_inline_highlighted_text(text, entities, show_label=show_label)
    display(HTML(html_block))

    if entities:
        display(pd.DataFrame(entities).sort_values(["start", "end"]).reset_index(drop=True))
    else:
        print("No entities detected.")

    return text, entities

show_pii_inline(idx=4, text_col="final_transcript.1", threshold=0.32, show_label=True)

from transformers import AutoTokenizer, AutoModelForTokenClassification, pipeline

model_name = "iiiorg/piiranha-v1-detect-personal-information"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForTokenClassification.from_pretrained(model_name)

ner = pipeline(
    "token-classification",
    model=model,
    tokenizer=tokenizer,
    aggregation_strategy="simple"
)

text = "John lives in New York. Email: john@gmail.com"

entities = ner(text)

for e in entities:
    print(e)

idx = 100
text = df.loc[idx, "final_transcript.1"]

piiranha_entities = ner(text)

for e in piiranha_entities:
    print(e)

print(text)

idx = 100

row = df.iloc[idx]

print("ROW ID:", row["id"])
print("CHANNEL:", row["channel"])

audio_path = f"/mnt/amc-data/pipeline/audio/sampled_channels/{row['id']}/{row['channel']}.wav"
print("AUDIO PATH:", audio_path)

from IPython.display import Audio
Audio(filename=audio_path)



"""## Forced Alignment with Wav2Vec2"""

import torch
import torchaudio

print(torch.__version__)
print(torchaudio.__version__)


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

import re
from dataclasses import dataclass
from pathlib import Path

import torch
import torchaudio
import pandas as pd
from IPython.display import Audio, display


# load once
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
bundle = torchaudio.pipelines.WAV2VEC2_ASR_BASE_960H
model = bundle.get_model().to(device)
labels = bundle.get_labels()
dictionary = {c: i for i, c in enumerate(labels)}
BLANK_ID = 0


def normalize_transcript_for_alignment(text, labels):
    """
    Convert transcript into the char format expected by the tutorial:
    |WORD|WORD|...
    Keeps only chars موجودة in the model label set.
    """
    text = str(text).upper().strip()

    # normalize whitespace
    text = re.sub(r"\s+", " ", text)

    # convert spaces to word boundary token
    text = text.replace(" ", "|")

    # keep only chars present in labels
    allowed = set(labels)
    text = "".join(ch for ch in text if ch in allowed)

    # force leading and trailing boundary for merge_words logic
    if not text.startswith("|"):
        text = "|" + text
    if not text.endswith("|"):
        text = text + "|"

    # compress repeated boundaries
    text = re.sub(r"\|+", "|", text)

    return text


def get_trellis(emission, tokens, blank_id=0):
    num_frame = emission.size(0)
    num_tokens = len(tokens)

    trellis = torch.zeros((num_frame, num_tokens))
    trellis[1:, 0] = torch.cumsum(emission[1:, blank_id], 0)
    trellis[0, 1:] = -float("inf")
    trellis[-num_tokens + 1 :, 0] = float("inf")

    for t in range(num_frame - 1):
        trellis[t + 1, 1:] = torch.maximum(
            trellis[t, 1:] + emission[t, blank_id],   # stay
            trellis[t, :-1] + emission[t, tokens[1:]] # change
        )
    return trellis


@dataclass
class Point:
    token_index: int
    time_index: int
    score: float


def backtrack(trellis, emission, tokens, blank_id=0):
    t, j = trellis.size(0) - 1, trellis.size(1) - 1

    path = [Point(j, t, emission[t, blank_id].exp().item())]
    while j > 0:
        assert t > 0

        p_stay = emission[t - 1, blank_id]
        p_change = emission[t - 1, tokens[j]]

        stayed = trellis[t - 1, j] + p_stay
        changed = trellis[t - 1, j - 1] + p_change

        t -= 1
        if changed > stayed:
            j -= 1

        prob = (p_change if changed > stayed else p_stay).exp().item()
        path.append(Point(j, t, prob))

    while t > 0:
        prob = emission[t - 1, blank_id].exp().item()
        path.append(Point(j, t - 1, prob))
        t -= 1

    return path[::-1]


@dataclass
class Segment:
    label: str
    start: int
    end: int
    score: float

    @property
    def length(self):
        return self.end - self.start


def merge_repeats(path, transcript):
    i1, i2 = 0, 0
    segments = []

    while i1 < len(path):
        while i2 < len(path) and path[i1].token_index == path[i2].token_index:
            i2 += 1

        score = sum(path[k].score for k in range(i1, i2)) / (i2 - i1)
        segments.append(
            Segment(
                transcript[path[i1].token_index],
                path[i1].time_index,
                path[i2 - 1].time_index + 1,
                score,
            )
        )
        i1 = i2

    return segments


def merge_words(segments, separator="|"):
    words = []
    i1, i2 = 0, 0

    while i1 < len(segments):
        if i2 >= len(segments) or segments[i2].label == separator:
            if i1 != i2:
                segs = segments[i1:i2]
                word = "".join(seg.label for seg in segs)
                score = sum(seg.score * seg.length for seg in segs) / sum(seg.length for seg in segs)
                words.append(
                    Segment(
                        word,
                        segments[i1].start,
                        segments[i2 - 1].end,
                        score,
                    )
                )
            i1 = i2 + 1
            i2 = i1
        else:
            i2 += 1

    return words


def align_from_df_index_torchaudio(
    idx,
    df,
    final_col="final_transcript.1",
    audio_template="/mnt/amc-data/pipeline/audio/sampled_channels/{id}/{channel}.wav",
):
    row = df.iloc[idx]

    transcript_raw = str(row[final_col]).strip()
    transcript = normalize_transcript_for_alignment(transcript_raw, labels)

    audio_path = audio_template.format(id=row["id"], channel=row["channel"])

    print("ROW INDEX:", idx)
    print("ROW ID:", row["id"])
    print("CHANNEL:", row["channel"])
    print("AUDIO PATH:", audio_path)
    print("\nFINAL TRANSCRIPT:\n")
    print(transcript_raw)
    print("\nALIGNMENT TRANSCRIPT:\n")
    print(transcript)

    display(Audio(filename=audio_path))

    waveform, sr = torchaudio.load(audio_path)

    # convert to mono if needed
    if waveform.size(0) > 1:
        waveform = waveform.mean(dim=0, keepdim=True)

    # resample if needed
    if sr != bundle.sample_rate:
        waveform = torchaudio.functional.resample(waveform, sr, bundle.sample_rate)
        sr = bundle.sample_rate

    with torch.inference_mode():
        emissions, _ = model(waveform.to(device))
        emissions = torch.log_softmax(emissions, dim=-1)

    emission = emissions[0].cpu().detach()

    tokens = [dictionary[c] for c in transcript]
    trellis = get_trellis(emission, tokens, blank_id=BLANK_ID)
    path = backtrack(trellis, emission, tokens, blank_id=BLANK_ID)
    segments = merge_repeats(path, transcript)
    word_segments = merge_words(segments)

    # map frame positions to seconds
    ratio = waveform.size(1) / trellis.size(0)

    rows = []
    for seg in word_segments:
        start_sample = int(ratio * seg.start)
        end_sample = int(ratio * seg.end)

        rows.append({
            "word": seg.label,
            "start": start_sample / sr,
            "end": end_sample / sr,
            "duration": (end_sample - start_sample) / sr,
            "score": seg.score,
        })

    word_df = pd.DataFrame(rows)
    display(word_df)

    return {
        "row": row,
        "audio_path": audio_path,
        "transcript_raw": transcript_raw,
        "transcript_aligned": transcript,
        "word_timestamps": word_df,
        "segments": word_segments,
        "waveform": waveform,
        "sample_rate": sr,
    }

idx = 100

result = align_from_df_index_torchaudio(
    idx=idx,
    df=df,
    final_col="final_transcript.1",
)

def play_aligned_word(result, word_idx):
    seg = result["segments"][word_idx]
    waveform = result["waveform"]
    sr = result["sample_rate"]

    # recompute sample boundaries same way
    transcript = result["transcript_aligned"]
    row_df = result["word_timestamps"]
    start = int(row_df.iloc[word_idx]["start"] * sr)
    end = int(row_df.iloc[word_idx]["end"] * sr)

    print(
        row_df.iloc[word_idx]["word"],
        f"{row_df.iloc[word_idx]['start']:.3f}s - {row_df.iloc[word_idx]['end']:.3f}s",
        f"score={row_df.iloc[word_idx]['score']:.3f}",
    )
    display(Audio(waveform[:, start:end].numpy(), rate=sr))

play_aligned_word(result, 0)

play_aligned_word(result, 1)

play_aligned_word(result, 2)

play_aligned_word(result, 3)

play_aligned_word(result, 4)

play_aligned_word(result, 5)

"""## Mask PII"""

import re
import json
from pathlib import Path
from difflib import SequenceMatcher

import numpy as np
import pandas as pd
import soundfile as sf
from IPython.display import Audio, display


# -----------------------------
# Helpers
# -----------------------------
def pick_final_col(df):
    for c in [
        "resolved_final_transcript",
        "final_transcript.1",
        "final_transcript",
        "review_final_transcript",
    ]:
        if c in df.columns:
            return c
    raise KeyError("No final transcript column found.")


def normalize_token(s):
    return re.sub(r"[^a-z0-9]+", "", str(s).lower())


def transcript_tokens_with_spans(text):
    """
    Tokenize transcript while keeping character spans.
    """
    text = str(text)
    pattern = re.compile(r"[A-Za-z0-9@._%+\-']+")
    rows = []
    for m in pattern.finditer(text):
        token = m.group(0)
        rows.append({
            "text": token,
            "start_char": m.start(),
            "end_char": m.end(),
            "norm": normalize_token(token),
        })
    return rows


# -----------------------------
# PII detection
# -----------------------------
EMAIL_RE = re.compile(r"\b[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[A-Za-z]{2,}\b")
PHONE_RE = re.compile(r"(?<!\d)(?:\+?1[-.\s]?)?(?:\(?\d{3}\)?[-.\s]?)?\d{3}[-.\s]?\d{4}(?!\d)")
SSN_RE = re.compile(r"\b\d{3}-\d{2}-\d{4}\b")
DOB_RE = re.compile(r"\b(?:0?[1-9]|1[0-2])[/-](?:0?[1-9]|[12]\d|3[01])[/-](?:\d{2}|\d{4})\b")
ZIP_RE = re.compile(r"\b\d{5}(?:-\d{4})?\b")

# contextual id-like values
ID_CONTEXT_RE = re.compile(
    r"\b(?:member|account|policy|reference|case|claim|mrn|subscriber|id)\s*(?:number|no\.?|#|id)?\s*[:\-]?\s*([A-Z0-9\-]{5,})\b",
    flags=re.IGNORECASE,
)


def detect_pii_regex(text):
    text = str(text)
    entities = []

    for m in EMAIL_RE.finditer(text):
        entities.append({"text": m.group(0), "type": "EMAIL", "start": m.start(), "end": m.end(), "source": "regex"})

    for m in PHONE_RE.finditer(text):
        entities.append({"text": m.group(0), "type": "PHONE", "start": m.start(), "end": m.end(), "source": "regex"})

    for m in SSN_RE.finditer(text):
        entities.append({"text": m.group(0), "type": "SSN", "start": m.start(), "end": m.end(), "source": "regex"})

    for m in DOB_RE.finditer(text):
        entities.append({"text": m.group(0), "type": "DOB", "start": m.start(), "end": m.end(), "source": "regex"})

    for m in ZIP_RE.finditer(text):
        entities.append({"text": m.group(0), "type": "ZIP", "start": m.start(), "end": m.end(), "source": "regex"})

    for m in ID_CONTEXT_RE.finditer(text):
        value = m.group(1)
        start = m.start(1)
        end = m.end(1)
        entities.append({"text": value, "type": "ID", "start": start, "end": end, "source": "regex"})

    return entities


def detect_pii_from_saved_json(row, transcript):
    """
    Reuse your saved pii_phi_json if it exists.
    Only keep PII category.
    Match all occurrences of the detected text in the transcript.
    """
    entities = []

    if "pii_phi_json" not in row or pd.isna(row["pii_phi_json"]) or not str(row["pii_phi_json"]).strip():
        return entities

    try:
        obj = json.loads(str(row["pii_phi_json"]))
    except Exception:
        return entities

    for ent in obj.get("entities", []):
        if not isinstance(ent, dict):
            continue

        if str(ent.get("category", "")).upper() != "PII":
            continue

        ent_text = str(ent.get("text", "")).strip()
        ent_type = str(ent.get("type", "PII")).strip().upper()

        if not ent_text:
            continue

        for m in re.finditer(re.escape(ent_text), transcript, flags=re.IGNORECASE):
            entities.append({
                "text": m.group(0),
                "type": ent_type,
                "start": m.start(),
                "end": m.end(),
                "source": "pii_phi_json",
            })

    return entities


def dedupe_entities(entities):
    seen = set()
    out = []
    for e in sorted(entities, key=lambda x: (x["start"], x["end"], x["type"], x["text"])):
        key = (e["start"], e["end"], e["type"], e["text"].lower())
        if key not in seen:
            out.append(e)
            seen.add(key)
    return out


# -----------------------------
# Map transcript spans -> aligned word times
# -----------------------------
def build_token_alignment(transcript_text, word_df):
    """
    Map transcript tokens to aligned word rows using normalized token sequence.
    """
    txt_tokens = transcript_tokens_with_spans(transcript_text)
    txt_norms = [t["norm"] for t in txt_tokens if t["norm"]]

    wd = word_df.copy()
    wd["norm"] = wd["word"].astype(str).map(normalize_token)
    wd = wd[wd["norm"] != ""].reset_index(drop=False)  # keep original row index

    word_norms = wd["norm"].tolist()

    # map transcript token index -> row index in word_df
    mapping = [None] * len(txt_tokens)

    txt_nonempty_positions = [i for i, t in enumerate(txt_tokens) if t["norm"]]
    sm = SequenceMatcher(None, txt_norms, word_norms)

    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            for a, b in zip(range(i1, i2), range(j1, j2)):
                mapping[txt_nonempty_positions[a]] = int(wd.iloc[b]["index"])
        elif tag == "replace":
            shared = min(i2 - i1, j2 - j1)
            for k in range(shared):
                mapping[txt_nonempty_positions[i1 + k]] = int(wd.iloc[j1 + k]["index"])

    return txt_tokens, mapping


def entities_to_time_ranges(entities, transcript_text, word_df, pad_sec=0.06):
    txt_tokens, mapping = build_token_alignment(transcript_text, word_df)

    rows = []
    for ent in entities:
        covered_token_idx = []
        for i, tok in enumerate(txt_tokens):
            overlap = not (tok["end_char"] <= ent["start"] or tok["start_char"] >= ent["end"])
            if overlap and mapping[i] is not None:
                covered_token_idx.append(mapping[i])

        if not covered_token_idx:
            continue

        sub = word_df.loc[sorted(set(covered_token_idx))]
        start = max(0.0, float(sub["start"].min()) - pad_sec)
        end = float(sub["end"].max()) + pad_sec

        rows.append({
            "text": ent["text"],
            "type": ent["type"],
            "source": ent["source"],
            "start": start,
            "end": end,
            "duration": end - start,
        })

    if not rows:
        return pd.DataFrame(columns=["text", "type", "source", "start", "end", "duration"])

    time_df = pd.DataFrame(rows).sort_values(["start", "end"]).reset_index(drop=True)
    return time_df


def merge_time_ranges(time_df):
    if time_df.empty:
        return time_df.copy()

    merged = []
    cur = time_df.iloc[0].to_dict()

    for _, row in time_df.iloc[1:].iterrows():
        if float(row["start"]) <= float(cur["end"]):
            cur["end"] = max(float(cur["end"]), float(row["end"]))
            cur["duration"] = float(cur["end"]) - float(cur["start"])
            cur["text"] = cur["text"] + " | " + row["text"]
            cur["type"] = cur["type"] + " | " + row["type"]
            cur["source"] = cur["source"] + " | " + row["source"]
        else:
            merged.append(cur)
            cur = row.to_dict()

    merged.append(cur)
    return pd.DataFrame(merged)


# -----------------------------
# Audio masking
# -----------------------------
def apply_beep_mask(audio, sr, spans, beep_freq=1000.0, beep_gain=0.25, fade_ms=8):
    x = np.array(audio, dtype=np.float32, copy=True)
    mono = False

    if x.ndim == 1:
        x = x[:, None]
        mono = True

    n_channels = x.shape[1]
    fade = max(1, int(sr * fade_ms / 1000))

    peak = np.max(np.abs(x)) if np.max(np.abs(x)) > 0 else 1.0
    amp = beep_gain * peak

    for _, r in spans.iterrows():
        s = max(0, int(float(r["start"]) * sr))
        e = min(len(x), int(float(r["end"]) * sr))
        if e <= s:
            continue

        n = e - s
        t = np.arange(n) / sr
        tone = amp * np.sin(2 * np.pi * beep_freq * t)

        if n > 2 * fade:
            env = np.ones(n, dtype=np.float32)
            env[:fade] = np.linspace(0, 1, fade)
            env[-fade:] = np.linspace(1, 0, fade)
            tone = tone * env

        tone = np.tile(tone[:, None], (1, n_channels))
        x[s:e, :] = tone

    if mono:
        x = x[:, 0]
    return x


def apply_silence_mask(audio, sr, spans):
    x = np.array(audio, dtype=np.float32, copy=True)
    for _, r in spans.iterrows():
        s = max(0, int(float(r["start"]) * sr))
        e = min(len(x), int(float(r["end"]) * sr))
        if e > s:
            x[s:e] = 0
    return x


# -----------------------------
# Main pipeline
# -----------------------------
def mask_pii_audio_from_alignment_result(
    idx,
    df,
    align_result,
    final_col="final_transcript.1",
    out_dir="masked_audio_outputs",
    mask_mode="beep",   # "beep" or "silence"
    use_saved_pii_json=True,
    play_masked=True,
):
    row = df.iloc[idx]
    transcript = str(row[final_col]).strip()
    word_df = align_result["word_timestamps"]
    audio_path = Path(align_result["audio_path"])

    # detect PII
    entities = detect_pii_regex(transcript)

    if use_saved_pii_json:
        entities += detect_pii_from_saved_json(row, transcript)

    entities = dedupe_entities(entities)
    entity_df = pd.DataFrame(entities)

    if entity_df.empty:
        print("No PII detected.")
        return {
            "row": row,
            "audio_path": audio_path,
            "transcript": transcript,
            "entity_df": entity_df,
            "time_df": pd.DataFrame(),
            "masked_audio_path": None,
        }

    # map to aligned time ranges
    time_df = entities_to_time_ranges(entities, transcript, word_df, pad_sec=0.06)
    merged_time_df = merge_time_ranges(time_df)

    print("Detected PII entities:")
    display(entity_df)

    print("Mapped time ranges:")
    display(merged_time_df)

    # load audio
    audio, sr = sf.read(str(audio_path), always_2d=False)

    # mask
    if mask_mode == "beep":
        masked = apply_beep_mask(audio, sr, merged_time_df)
    elif mask_mode == "silence":
        masked = apply_silence_mask(audio, sr, merged_time_df)
    else:
        raise ValueError("mask_mode must be 'beep' or 'silence'")

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{row['id']}_{row['channel']}_idx{idx}_masked.wav"

    sf.write(str(out_path), masked, sr)

    print("Masked audio saved to:", out_path)

    if play_masked:
        display(Audio(filename=str(out_path)))

    return {
        "row": row,
        "audio_path": audio_path,
        "transcript": transcript,
        "entity_df": entity_df,
        "time_df": merged_time_df,
        "masked_audio_path": out_path,
    }

idx = 100
align_result = align_from_df_index_torchaudio(
    idx=idx,
    df=df,
    final_col="final_transcript.1",
)

masked_result = mask_pii_audio_from_alignment_result(
    idx=idx,
    df=df,
    align_result=align_result,
    final_col="final_transcript.1",
    mask_mode="beep",   # or "silence"
    use_saved_pii_json=True,
)

print("RAW TRANSCRIPT:\n", align_result["transcript_raw"])
print("\nALIGNED TRANSCRIPT:\n", align_result["transcript_aligned"])

print("\nDetected entities:")
display(masked_result["entity_df"])

print("\nMapped time ranges:")
display(masked_result["time_df"])

# !pip install spacy
!python3 -m spacy download en_core_web_sm

import spacy

spacy_nlp = spacy.load("en_core_web_sm")

# pip install soundfile gliner transformers accelerate if needed
# optional:
# pip install spacy
# python -m spacy download en_core_web_sm

import re
import json
import html
import textwrap
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import soundfile as sf
import torch
import torchaudio
from gliner import GLiNER
from transformers import AutoTokenizer, AutoModelForTokenClassification, pipeline
from IPython.display import Audio, display, HTML

# -----------------------------------------------------------------------------
# Optional spaCy fallback
# -----------------------------------------------------------------------------
try:
    import spacy
    try:
        spacy_nlp = spacy.load("en_core_web_sm")
    except Exception:
        spacy_nlp = None
except Exception:
    spacy_nlp = None


# -----------------------------------------------------------------------------
# Load models once
# -----------------------------------------------------------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

bundle = torchaudio.pipelines.WAV2VEC2_ASR_BASE_960H
asr_model = bundle.get_model().to(device).eval()
labels = bundle.get_labels()
dictionary = {c: i for i, c in enumerate(labels)}
BLANK_ID = 0

gliner_model = GLiNER.from_pretrained("knowledgator/gliner-pii-large-v1.0")

# Piiranha
try:
    piiranha_device = 0 if torch.cuda.is_available() else -1
    piiranha_pipe = pipeline(
        "token-classification",
        model="iiiorg/piiranha-v1-detect-personal-information",
        tokenizer="iiiorg/piiranha-v1-detect-personal-information",
        aggregation_strategy="simple",
        device=piiranha_device,
    )
except Exception as e:
    print("Warning: Piiranha failed to load. Continuing without it.")
    print(e)
    piiranha_pipe = None


# -----------------------------------------------------------------------------
# Config
# -----------------------------------------------------------------------------
GLINER_LABELS = [
    "person name",
    "age",
    "location",
    "phone number",
    "aadhaar number",
    "email address",
    "insurance id",
    "doctor name",
    "institution name",
]

LABEL_STYLES = {
    "person name":        {"bg": "#ffd6d6", "border": "#ef4444"},
    "age":                {"bg": "#dcfce7", "border": "#22c55e"},
    "location":           {"bg": "#dbeafe", "border": "#3b82f6"},
    "phone number":       {"bg": "#ede9fe", "border": "#8b5cf6"},
    "aadhaar number":     {"bg": "#ccfbf1", "border": "#14b8a6"},
    "email address":      {"bg": "#fbcfe8", "border": "#ec4899"},
    "insurance id":       {"bg": "#fecdd3", "border": "#f43f5e"},
    "doctor name":        {"bg": "#d1fae5", "border": "#10b981"},
    "institution name":   {"bg": "#dbeafe", "border": "#3b82f6"},
    "account number":     {"bg": "#fde68a", "border": "#d97706"},
    "credit card number": {"bg": "#fca5a5", "border": "#dc2626"},
    "id number":          {"bg": "#c7d2fe", "border": "#4f46e5"},
    "ssn":                {"bg": "#fecaca", "border": "#b91c1c"},
    "username":           {"bg": "#ddd6fe", "border": "#7c3aed"},
    "password":           {"bg": "#f9a8d4", "border": "#db2777"},
    "zipcode":            {"bg": "#bfdbfe", "border": "#2563eb"},
    "date":               {"bg": "#fef3c7", "border": "#eab308"},
}
DEFAULT_STYLE = {"bg": "#e5e7eb", "border": "#6b7280"}

DIGIT_WORDS_UPPER = {
    "0": "ZERO", "1": "ONE", "2": "TWO", "3": "THREE", "4": "FOUR",
    "5": "FIVE", "6": "SIX", "7": "SEVEN", "8": "EIGHT", "9": "NINE",
}
DIGIT_WORDS_LOWER = {
    "0": "zero", "1": "one", "2": "two", "3": "three", "4": "four",
    "5": "five", "6": "six", "7": "seven", "8": "eight", "9": "nine",
}

PIIRANHA_LABEL_MAP = {
    "ACCOUNTNUM": "account number",
    "BUILDINGNUM": "location",
    "CITY": "location",
    "CREDITCARDNUMBER": "credit card number",
    "DATEOFBIRTH": "date",
    "DRIVERLICENSENUM": "id number",
    "EMAIL": "email address",
    "GIVENNAME": "person name",
    "IDCARDNUM": "id number",
    "PASSWORD": "password",
    "SOCIALNUM": "ssn",
    "STREET": "location",
    "SURNAME": "person name",
    "TAXNUM": "id number",
    "TELEPHONENUM": "phone number",
    "USERNAME": "username",
    "ZIPCODE": "zipcode",
}

MASK_TYPE_PRIORITY = {
    "PHONE": 1,
    "EMAIL": 2,
    "SSN": 3,
    "DOB": 4,
    "AADHAAR_NUMBER": 5,
    "INSURANCE_ID": 6,
    "ACCOUNT_NUMBER": 7,
    "CREDIT_CARD_NUMBER": 8,
    "ID_NUMBER": 9,
    "ID": 10,
    "ZIP": 11,
    "ZIPCODE": 12,
    "PERSON_NAME": 13,
    "DOCTOR_NAME": 14,
    "USERNAME": 15,
    "PASSWORD": 16,
    "INSTITUTION_NAME": 17,
    "LOCATION": 18,
    "DATE": 19,
}


# -----------------------------------------------------------------------------
# Basic helpers
# -----------------------------------------------------------------------------
def pick_final_col(df):
    for c in [
        "final_transcript.1",
        "resolved_final_transcript",
        "final_transcript",
        "review_final_transcript",
    ]:
        if c in df.columns:
            return c
    raise KeyError("No final transcript column found.")


def normalize_token(s):
    return re.sub(r"[^a-z0-9]+", "", str(s).lower())


def dedupe_entities(entities):
    seen = set()
    out = []
    for e in sorted(entities, key=lambda x: (x["start"], x["end"], x.get("type", ""), x["text"].lower())):
        key = (e["start"], e["end"], e.get("type", ""), e["text"].lower())
        if key not in seen:
            seen.add(key)
            out.append(e)
    return out


def resolve_overlaps(entities):
    entities = sorted(
        entities,
        key=lambda x: (x["start"], -(x["end"] - x["start"]), -x.get("score", 0.0))
    )

    kept = []
    for ent in entities:
        has_overlap = False
        replace_idx = None

        for i, k in enumerate(kept):
            overlap = not (ent["end"] <= k["start"] or ent["start"] >= k["end"])
            if overlap:
                has_overlap = True
                if ent.get("score", 0.0) > k.get("score", 0.0):
                    replace_idx = i
                break

        if not has_overlap:
            kept.append(ent)
        elif replace_idx is not None:
            kept[replace_idx] = ent

    return sorted(kept, key=lambda x: x["start"])


def dedupe_mask_entities(entities):
    best = {}

    for e in entities:
        key = (e["start"], e["end"], str(e["text"]).strip().lower())
        cur = best.get(key)

        if cur is None:
            best[key] = e
            continue

        cur_pri = MASK_TYPE_PRIORITY.get(cur["type"], 999)
        new_pri = MASK_TYPE_PRIORITY.get(e["type"], 999)

        if new_pri < cur_pri:
            best[key] = e

    return sorted(best.values(), key=lambda x: (x["start"], x["end"]))


# -----------------------------------------------------------------------------
# GLiNER helpers
# -----------------------------------------------------------------------------
def detect_pii_gliner(text, threshold=0.35):
    text = str(text)
    raw_entities = gliner_model.predict_entities(text, GLINER_LABELS, threshold=threshold)

    entities = []
    for e in raw_entities:
        entities.append({
            "text": str(e["text"]),
            "label": str(e["label"]),
            "start": int(e["start"]),
            "end": int(e["end"]),
            "score": float(e.get("score", 0.0)),
            "source": "gliner",
        })

    return resolve_overlaps(entities)


# -----------------------------------------------------------------------------
# Rule-based name extraction
# -----------------------------------------------------------------------------
NAME_BLACKLIST = {
    "nurse", "assistant", "doctor", "agent", "representative", "coordinator",
    "service", "health", "calling", "message", "program", "care", "customer",
    "member", "patient", "blue", "cross", "shield", "amc", "voicemail",
    "appointment", "medication", "phone", "number", "my", "name", "is"
}

NAME_PATTERNS = [
    re.compile(
        r"\bthis message is for\s+([a-z]+(?:\s+[a-z]+){0,2}?)(?=\s+(?:my name is|this is|i am|i'm|calling|from|with|and)\b|[.,;!?]|$)",
        flags=re.IGNORECASE,
    ),
    re.compile(
        r"\bmy name is\s+([a-z]+(?:\s+[a-z]+){0,2}?)(?=\s+(?:i am|i'm|calling|from|with|and|on behalf)\b|[.,;!?]|$)",
        flags=re.IGNORECASE,
    ),
    re.compile(
        r"\bthis is\s+([a-z]+(?:\s+[a-z]+){0,2}?)(?=\s+(?:i am|i'm|calling|from|with|and|on behalf)\b|[.,;!?]|$)",
        flags=re.IGNORECASE,
    ),
    re.compile(
        r"\bspeaking with\s+([a-z]+(?:\s+[a-z]+){0,2}?)(?=\s+(?:from|at|and)\b|[.,;!?]|$)",
        flags=re.IGNORECASE,
    ),
]


def likely_person_name(span_text):
    toks = str(span_text).strip().lower().split()

    if not toks or len(toks) > 3:
        return False
    if any(len(t) < 2 for t in toks):
        return False
    if any(t in NAME_BLACKLIST for t in toks):
        return False
    return True


def detect_rule_person_names(text):
    text = str(text)
    entities = []

    for pat in NAME_PATTERNS:
        for m in pat.finditer(text):
            span = text[m.start(1):m.end(1)].strip()
            span = re.sub(r"\s+", " ", span)

            if not likely_person_name(span):
                continue

            entities.append({
                "text": span,
                "label": "person name",
                "start": m.start(1),
                "end": m.end(1),
                "score": 0.99,
                "source": "rule_name",
            })

    return resolve_overlaps(entities)


# -----------------------------------------------------------------------------
# Optional spaCy fallback
# -----------------------------------------------------------------------------
SPACY_LABEL_MAP = {
    "ORG": "institution name",
    "GPE": "location",
    "LOC": "location",
}

def detect_pii_spacy_fallback(text):
    if spacy_nlp is None:
        return []

    text = str(text)
    doc = spacy_nlp(text)

    entities = []
    for ent in doc.ents:
        if ent.label_ not in SPACY_LABEL_MAP:
            continue

        entities.append({
            "text": ent.text,
            "label": SPACY_LABEL_MAP[ent.label_],
            "start": int(ent.start_char),
            "end": int(ent.end_char),
            "score": 0.60,
            "source": "spacy",
        })

    return resolve_overlaps(entities)


# -----------------------------------------------------------------------------
# Piiranha fallback
# -----------------------------------------------------------------------------
def detect_pii_piiranha(text, threshold=0.45):
    if piiranha_pipe is None:
        return []

    text = str(text)
    raw = piiranha_pipe(text)

    entities = []
    for e in raw:
        raw_label = str(e.get("entity_group", e.get("entity", ""))).upper()
        score = float(e.get("score", 0.0))

        if score < threshold:
            continue
        if raw_label not in PIIRANHA_LABEL_MAP:
            continue

        start = int(e.get("start", -1))
        end = int(e.get("end", -1))
        if start < 0 or end <= start:
            continue

        entities.append({
            "text": text[start:end],
            "label": PIIRANHA_LABEL_MAP[raw_label],
            "start": start,
            "end": end,
            "score": score,
            "source": "piiranha",
            "raw_label": raw_label,
        })

    return resolve_overlaps(entities)


# -----------------------------------------------------------------------------
# Display helpers
# -----------------------------------------------------------------------------
def render_inline_highlighted_text(text, entities, show_label=False):
    out = []
    cursor = 0

    for ent in entities:
        start = ent["start"]
        end = ent["end"]
        label = ent["label"]
        style = LABEL_STYLES.get(label, DEFAULT_STYLE)

        if cursor < start:
            out.append(html.escape(text[cursor:start]))

        span_text = html.escape(text[start:end])

        if show_label:
            out.append(
                f"""<span style="
                    background:{style['bg']};
                    border:1px solid {style['border']};
                    border-radius:4px;
                    padding:1px 3px;
                    margin:0 1px;
                    display:inline-block;
                ">{span_text}<span style="
                    font-size:10px;
                    font-weight:bold;
                    margin-left:4px;
                    color:#111827;
                ">[{html.escape(label)}]</span></span>"""
            )
        else:
            out.append(
                f"""<span style="
                    background:{style['bg']};
                    border-radius:3px;
                    padding:1px 2px;
                ">{span_text}</span>"""
            )

        cursor = end

    if cursor < len(text):
        out.append(html.escape(text[cursor:]))

    return f"""
    <div style="
        background:#ffffff;
        color:#111827;
        border:1px solid #d1d5db;
        border-radius:8px;
        padding:14px 16px;
        line-height:1.9;
        font-size:18px;
        white-space:pre-wrap;
        word-wrap:break-word;
    ">
        {''.join(out)}
    </div>
    """


def display_entities_to_mask_entities(display_entities):
    out = []
    for e in display_entities:
        out.append({
            "text": e["text"],
            "type": str(e["label"]).upper().replace(" ", "_"),
            "start": e["start"],
            "end": e["end"],
            "source": e.get("source", "display_detector"),
        })
    return out


def detect_pii_hybrid(text, gliner_threshold=0.35, piiranha_threshold=0.45):
    text = str(text)

    gliner_entities = detect_pii_gliner(text, threshold=gliner_threshold)
    rule_entities = detect_rule_person_names(text)
    spacy_entities = detect_pii_spacy_fallback(text)
    piiranha_entities = detect_pii_piiranha(text, threshold=piiranha_threshold)

    return resolve_overlaps(
        gliner_entities + rule_entities + spacy_entities + piiranha_entities
    )


def show_pii_inline(idx, df, text_col=None, gliner_threshold=0.35, piiranha_threshold=0.45, show_label=True):
    text_col = text_col or pick_final_col(df)

    if idx < 0 or idx >= len(df):
        raise IndexError(f"Index {idx} out of range. Valid: 0 to {len(df)-1}")
    if text_col not in df.columns:
        raise KeyError(f"Column '{text_col}' not found")

    text = df.loc[idx, text_col]
    if pd.isna(text) or not str(text).strip():
        raise ValueError(f"Empty text at row {idx}")

    text = str(text)
    entities = detect_pii_hybrid(text, gliner_threshold=gliner_threshold, piiranha_threshold=piiranha_threshold)

    print(f"Row index: {idx}")
    print(f"Detected entities: {len(entities)}")

    display(HTML(render_inline_highlighted_text(text, entities, show_label=show_label)))
    if entities:
        display(pd.DataFrame(entities))

    return text, entities


# -----------------------------------------------------------------------------
# Digit expansion and transcript normalization for alignment
# -----------------------------------------------------------------------------
def expand_digits_to_words(text):
    text = str(text)

    def repl(match):
        digits = match.group(0)
        return " " + " ".join(DIGIT_WORDS_UPPER[d] for d in digits) + " "

    return re.sub(r"\d+", repl, text)


def normalize_transcript_for_alignment(text, labels):
    text = str(text).upper().strip()
    text = expand_digits_to_words(text)
    text = re.sub(r"\s+", " ", text)
    text = text.replace(" ", "|")

    allowed = set(labels)
    text = "".join(ch for ch in text if ch in allowed)

    if not text.startswith("|"):
        text = "|" + text
    if not text.endswith("|"):
        text = text + "|"

    text = re.sub(r"\|+", "|", text)
    return text


# -----------------------------------------------------------------------------
# Torchaudio forced alignment
# -----------------------------------------------------------------------------
def get_trellis(emission, tokens, blank_id=0):
    num_frame = emission.size(0)
    num_tokens = len(tokens)

    trellis = torch.zeros((num_frame, num_tokens))
    trellis[1:, 0] = torch.cumsum(emission[1:, blank_id], 0)
    trellis[0, 1:] = -float("inf")
    trellis[-num_tokens + 1:, 0] = float("inf")

    for t in range(num_frame - 1):
        trellis[t + 1, 1:] = torch.maximum(
            trellis[t, 1:] + emission[t, blank_id],
            trellis[t, :-1] + emission[t, tokens[1:]],
        )
    return trellis


@dataclass
class Point:
    token_index: int
    time_index: int
    score: float


def backtrack(trellis, emission, tokens, blank_id=0):
    t, j = trellis.size(0) - 1, trellis.size(1) - 1

    path = [Point(j, t, emission[t, blank_id].exp().item())]
    while j > 0:
        assert t > 0

        p_stay = emission[t - 1, blank_id]
        p_change = emission[t - 1, tokens[j]]

        stayed = trellis[t - 1, j] + p_stay
        changed = trellis[t - 1, j - 1] + p_change

        t -= 1
        if changed > stayed:
            j -= 1

        prob = (p_change if changed > stayed else p_stay).exp().item()
        path.append(Point(j, t, prob))

    while t > 0:
        prob = emission[t - 1, blank_id].exp().item()
        path.append(Point(j, t - 1, prob))
        t -= 1

    return path[::-1]


@dataclass
class Segment:
    label: str
    start: int
    end: int
    score: float

    @property
    def length(self):
        return self.end - self.start


def merge_repeats(path, transcript):
    i1, i2 = 0, 0
    segments = []

    while i1 < len(path):
        while i2 < len(path) and path[i1].token_index == path[i2].token_index:
            i2 += 1

        score = sum(path[k].score for k in range(i1, i2)) / (i2 - i1)
        segments.append(
            Segment(
                transcript[path[i1].token_index],
                path[i1].time_index,
                path[i2 - 1].time_index + 1,
                score,
            )
        )
        i1 = i2

    return segments


def merge_words(segments, separator="|"):
    words = []
    i1, i2 = 0, 0

    while i1 < len(segments):
        if i2 >= len(segments) or segments[i2].label == separator:
            if i1 != i2:
                segs = segments[i1:i2]
                word = "".join(seg.label for seg in segs)
                score = sum(seg.score * seg.length for seg in segs) / sum(seg.length for seg in segs)
                words.append(
                    Segment(
                        word,
                        segments[i1].start,
                        segments[i2 - 1].end,
                        score,
                    )
                )
            i1 = i2 + 1
            i2 = i1
        else:
            i2 += 1

    return words


def force_align_audio_and_transcript(audio_path, transcript_raw):
    transcript_aligned = normalize_transcript_for_alignment(transcript_raw, labels)

    waveform, sr = torchaudio.load(str(audio_path))

    if waveform.size(0) > 1:
        waveform = waveform.mean(dim=0, keepdim=True)

    if sr != bundle.sample_rate:
        waveform = torchaudio.functional.resample(waveform, sr, bundle.sample_rate)
        sr = bundle.sample_rate

    with torch.inference_mode():
        emissions, _ = asr_model(waveform.to(device))
        emissions = torch.log_softmax(emissions, dim=-1)

    emission = emissions[0].cpu().detach()

    tokens = [dictionary[c] for c in transcript_aligned]
    trellis = get_trellis(emission, tokens, blank_id=BLANK_ID)
    path = backtrack(trellis, emission, tokens, blank_id=BLANK_ID)
    segments = merge_repeats(path, transcript_aligned)
    word_segments = merge_words(segments)

    ratio = waveform.size(1) / trellis.size(0)

    rows = []
    for seg in word_segments:
        start_sample = int(ratio * seg.start)
        end_sample = int(ratio * seg.end)

        rows.append({
            "word": seg.label,
            "start": start_sample / sr,
            "end": end_sample / sr,
            "duration": (end_sample - start_sample) / sr,
            "score": seg.score,
        })

    if rows:
        word_df = pd.DataFrame(rows)
    else:
        word_df = pd.DataFrame(columns=["word", "start", "end", "duration", "score"])

    return {
        "transcript_raw": transcript_raw,
        "transcript_aligned": transcript_aligned,
        "word_timestamps": word_df,
        "segments": word_segments,
        "waveform": waveform,
        "sample_rate": sr,
    }


# -----------------------------------------------------------------------------
# Regex + saved-json PII detection
# -----------------------------------------------------------------------------
EMAIL_RE = re.compile(r"\b[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[A-Za-z]{2,}\b")
PHONE_RE = re.compile(r"(?<!\d)(?:\+?1[-.\s]?)?(?:\(?\d{3}\)?[-.\s]?)?\d{3}[-.\s]?\d{4}(?!\d)")
SSN_RE = re.compile(r"\b\d{3}-\d{2}-\d{4}\b")
DOB_RE = re.compile(r"\b(?:0?[1-9]|1[0-2])[/-](?:0?[1-9]|[12]\d|3[01])[/-](?:\d{2}|\d{4})\b")
ZIP_RE = re.compile(r"\b\d{5}(?:-\d{4})?\b")

ID_CONTEXT_RE = re.compile(
    r"\b(?:member|account|policy|reference|case|claim|mrn|subscriber|insurance)\s*"
    r"(?:number|no\.?|#|id)?\s*[:\-]?\s*([A-Z0-9\-]{4,})\b",
    flags=re.IGNORECASE,
)

BAD_ID_WORDS = {
    "number", "member", "account", "policy", "reference", "case",
    "claim", "subscriber", "insurance", "id", "no"
}


def is_valid_id_candidate(value):
    value = str(value).strip()
    norm = re.sub(r"[^A-Za-z0-9]", "", value).lower()

    if not norm:
        return False
    if norm in BAD_ID_WORDS:
        return False
    if norm.isalpha():
        return False
    if len(norm) < 4:
        return False
    return any(ch.isdigit() for ch in norm)


def detect_pii_regex(text):
    text = str(text)
    entities = []

    for m in EMAIL_RE.finditer(text):
        entities.append({"text": m.group(0), "type": "EMAIL", "start": m.start(), "end": m.end(), "source": "regex"})

    for m in PHONE_RE.finditer(text):
        entities.append({"text": m.group(0), "type": "PHONE", "start": m.start(), "end": m.end(), "source": "regex"})

    for m in SSN_RE.finditer(text):
        entities.append({"text": m.group(0), "type": "SSN", "start": m.start(), "end": m.end(), "source": "regex"})

    for m in DOB_RE.finditer(text):
        entities.append({"text": m.group(0), "type": "DOB", "start": m.start(), "end": m.end(), "source": "regex"})

    for m in ZIP_RE.finditer(text):
        entities.append({"text": m.group(0), "type": "ZIP", "start": m.start(), "end": m.end(), "source": "regex"})

    for m in ID_CONTEXT_RE.finditer(text):
        value = m.group(1)
        if not is_valid_id_candidate(value):
            continue

        entities.append({
            "text": value,
            "type": "ID",
            "start": m.start(1),
            "end": m.end(1),
            "source": "regex",
        })

    return entities


def detect_pii_from_saved_json(row, transcript):
    entities = []

    if "pii_phi_json" not in row or pd.isna(row["pii_phi_json"]) or not str(row["pii_phi_json"]).strip():
        return entities

    try:
        obj = json.loads(str(row["pii_phi_json"]))
    except Exception:
        return entities

    for ent in obj.get("entities", []):
        if not isinstance(ent, dict):
            continue
        if str(ent.get("category", "")).upper() != "PII":
            continue

        ent_text = str(ent.get("text", "")).strip()
        ent_type = str(ent.get("type", "PII")).strip().upper()

        if not ent_text:
            continue

        for m in re.finditer(re.escape(ent_text), transcript, flags=re.IGNORECASE):
            entities.append({
                "text": m.group(0),
                "type": ent_type,
                "start": m.start(),
                "end": m.end(),
                "source": "pii_phi_json",
            })

    return entities


# -----------------------------------------------------------------------------
# Map entities to aligned timestamps
# -----------------------------------------------------------------------------
def entity_to_search_tokens(text):
    raw_tokens = re.findall(r"[A-Za-z0-9@._%+\-']+", str(text))
    out = []

    for tok in raw_tokens:
        norm = normalize_token(tok)
        if not norm:
            continue

        if norm.isdigit():
            out.extend(DIGIT_WORDS_LOWER[d] for d in norm)
        else:
            out.append(norm)

    return out


def entities_to_time_ranges(entities, word_df, pad_sec=0.08, min_duration=0.25):
    if word_df is None or not isinstance(word_df, pd.DataFrame) or word_df.empty:
        print("No aligned word timestamps available.")
        return pd.DataFrame(columns=["text", "type", "source", "start", "end", "duration"])

    required = ["word", "start", "end"]
    missing = [c for c in required if c not in word_df.columns]
    if missing:
        print("Alignment output is missing columns:", missing)
        print("Available columns:", list(word_df.columns))
        return pd.DataFrame(columns=["text", "type", "source", "start", "end", "duration"])

    wd = word_df.copy()
    wd["norm"] = wd["word"].astype(str).map(normalize_token)
    wd = wd[wd["norm"] != ""].reset_index(drop=True)

    if wd.empty:
        print("Aligned word timestamps exist but contain no usable words.")
        return pd.DataFrame(columns=["text", "type", "source", "start", "end", "duration"])

    word_norms = wd["norm"].tolist()
    rows = []

    for ent in entities:
        search_toks = entity_to_search_tokens(ent["text"])
        if not search_toks:
            continue

        found_any = False
        n = len(search_toks)

        for i in range(len(word_norms) - n + 1):
            if word_norms[i:i+n] == search_toks:
                start = max(0.0, float(wd.iloc[i]["start"]) - pad_sec)
                end = float(wd.iloc[i+n-1]["end"]) + pad_sec

                if end - start < min_duration:
                    mid = (start + end) / 2
                    start = max(0.0, mid - min_duration / 2)
                    end = mid + min_duration / 2

                rows.append({
                    "text": ent["text"],
                    "type": ent["type"],
                    "source": ent["source"],
                    "start": start,
                    "end": end,
                    "duration": end - start,
                })
                found_any = True

        if not found_any:
            print("Could not map entity to timestamps:", ent["text"], "| type:", ent["type"])

    if not rows:
        return pd.DataFrame(columns=["text", "type", "source", "start", "end", "duration"])

    return pd.DataFrame(rows).sort_values(["start", "end"]).reset_index(drop=True)


def merge_time_ranges(time_df):
    if time_df is None or time_df.empty:
        return pd.DataFrame(columns=["text", "type", "source", "start", "end", "duration"])

    merged = []
    cur = time_df.iloc[0].to_dict()

    for _, row in time_df.iloc[1:].iterrows():
        if float(row["start"]) <= float(cur["end"]):
            cur["end"] = max(float(cur["end"]), float(row["end"]))
            cur["duration"] = float(cur["end"]) - float(cur["start"])
        else:
            merged.append(cur)
            cur = row.to_dict()

    merged.append(cur)
    return pd.DataFrame(merged)


# -----------------------------------------------------------------------------
# Audio masking
# -----------------------------------------------------------------------------
def apply_beep_mask(audio, sr, spans, beep_freq=1000.0, beep_gain=0.35, fade_ms=8):
    x = np.array(audio, dtype=np.float32, copy=True)
    mono = False

    if x.ndim == 1:
        x = x[:, None]
        mono = True

    n_channels = x.shape[1]
    fade = max(1, int(sr * fade_ms / 1000))
    peak = np.max(np.abs(x)) if np.max(np.abs(x)) > 0 else 1.0
    amp = beep_gain * peak

    for _, r in spans.iterrows():
        s = max(0, int(float(r["start"]) * sr))
        e = min(len(x), int(float(r["end"]) * sr))
        if e <= s:
            continue

        n = e - s
        t = np.arange(n) / sr
        tone = amp * np.sin(2 * np.pi * beep_freq * t)

        if n > 2 * fade:
            env = np.ones(n, dtype=np.float32)
            env[:fade] = np.linspace(0, 1, fade)
            env[-fade:] = np.linspace(1, 0, fade)
            tone = tone * env

        tone = np.tile(tone[:, None], (1, n_channels))
        x[s:e, :] = tone

    if mono:
        x = x[:, 0]
    return x


def apply_silence_mask(audio, sr, spans):
    x = np.array(audio, dtype=np.float32, copy=True)
    mono = False

    if x.ndim == 1:
        x = x[:, None]
        mono = True

    for _, r in spans.iterrows():
        s = max(0, int(float(r["start"]) * sr))
        e = min(len(x), int(float(r["end"]) * sr))
        if e > s:
            x[s:e, :] = 0.0

    if mono:
        x = x[:, 0]
    return x


# -----------------------------------------------------------------------------
# Detection ensemble
# -----------------------------------------------------------------------------
def detect_pii_ensemble(
    text,
    row=None,
    gliner_threshold=0.35,
    piiranha_threshold=0.45,
    use_saved_pii_json=True,
):
    text = str(text)

    display_entities = detect_pii_hybrid(
        text,
        gliner_threshold=gliner_threshold,
        piiranha_threshold=piiranha_threshold,
    )

    mask_entities = []
    mask_entities += detect_pii_regex(text)
    mask_entities += display_entities_to_mask_entities(display_entities)

    if row is not None and use_saved_pii_json:
        mask_entities += detect_pii_from_saved_json(row, text)

    mask_entities = dedupe_mask_entities(mask_entities)
    return display_entities, mask_entities


# -----------------------------------------------------------------------------
# Main function
# -----------------------------------------------------------------------------
def align_mask_and_show_pii_from_df_index(
    idx,
    df,
    final_col=None,
    audio_template="/mnt/amc-data/pipeline/audio/sampled_channels/{id}/{channel}.wav",
    use_saved_pii_json=True,
    gliner_threshold=0.35,
    piiranha_threshold=0.45,
    show_label=True,
    mask_mode="beep",   # "beep" or "silence"
    out_dir="masked_audio_outputs",
    play_original=True,
    play_masked=True,
):
    final_col = final_col or pick_final_col(df)
    row = df.iloc[idx]
    transcript = str(row[final_col]).strip()
    audio_path = Path(audio_template.format(id=row["id"], channel=row["channel"]))

    print("=" * 100)
    print("ROW INDEX   :", idx)
    print("ROW ID      :", row["id"])
    print("CHANNEL     :", row["channel"])
    print("AUDIO PATH  :", audio_path)
    print("FINAL COL   :", final_col)
    print("=" * 100)
    print("\nFINAL TRANSCRIPT:\n")
    print(textwrap.fill(transcript, width=120))
    print()

    if not audio_path.exists():
        raise FileNotFoundError(f"Audio file not found: {audio_path}")

    # 1. Detection ensemble
    display_entities, mask_entities = detect_pii_ensemble(
        transcript,
        row=row,
        gliner_threshold=gliner_threshold,
        piiranha_threshold=piiranha_threshold,
        use_saved_pii_json=use_saved_pii_json,
    )

    print("ENSEMBLE PII HIGHLIGHT:\n")
    display(HTML(render_inline_highlighted_text(
        transcript,
        display_entities,
        show_label=show_label,
    )))
    display(
        pd.DataFrame(display_entities)
        if display_entities
        else pd.DataFrame(columns=["text", "label", "start", "end", "score", "source"])
    )
    print()

    if play_original:
        print("Original audio:")
        display(Audio(filename=str(audio_path)))
        print()

    # 2. Force alignment
    align_result = force_align_audio_and_transcript(audio_path, transcript)

    print("ALIGNED TRANSCRIPT:\n")
    print(align_result["transcript_aligned"])
    print()

    print("WORD TIMESTAMPS:")
    display(align_result["word_timestamps"])
    print()

    # 3. Masking entities
    entity_df = pd.DataFrame(mask_entities)

    print("MASKING ENTITIES:")
    display(
        entity_df
        if not entity_df.empty
        else pd.DataFrame(columns=["text", "type", "start", "end", "source"])
    )
    print()

    if entity_df.empty:
        print("No PII found to mask.")
        return {
            "row": row,
            "audio_path": audio_path,
            "transcript": transcript,
            "align_result": align_result,
            "display_entity_df": pd.DataFrame(display_entities),
            "entity_df": entity_df,
            "time_df": pd.DataFrame(),
            "masked_audio_path": None,
        }

    # 4. Map to time ranges
    time_df = merge_time_ranges(
        entities_to_time_ranges(
            mask_entities,
            align_result["word_timestamps"],
            pad_sec=0.08,
            min_duration=0.25,
        )
    )

    print("MAPPED TIME RANGES:")
    display(
        time_df
        if not time_df.empty
        else pd.DataFrame(columns=["text", "type", "source", "start", "end", "duration"])
    )
    print()

    if time_df.empty:
        print("No PII entities could be mapped to timestamps. Audio not masked.")
        return {
            "row": row,
            "audio_path": audio_path,
            "transcript": transcript,
            "align_result": align_result,
            "display_entity_df": pd.DataFrame(display_entities),
            "entity_df": entity_df,
            "time_df": time_df,
            "masked_audio_path": None,
        }

    # 5. Mask audio
    audio, sr = sf.read(str(audio_path), always_2d=False)

    if mask_mode == "beep":
        masked_audio = apply_beep_mask(audio, sr, time_df)
    elif mask_mode == "silence":
        masked_audio = apply_silence_mask(audio, sr, time_df)
    else:
        raise ValueError("mask_mode must be 'beep' or 'silence'")

    Path(out_dir).mkdir(parents=True, exist_ok=True)
    out_path = Path(out_dir) / f"{row['id']}_{row['channel']}_idx{idx}_masked.wav"
    sf.write(str(out_path), masked_audio, sr)

    print("MASKED AUDIO SAVED TO:")
    print(out_path)
    print()

    if play_masked:
        print("Masked audio:")
        display(Audio(filename=str(out_path)))

    return {
        "row": row,
        "audio_path": audio_path,
        "transcript": transcript,
        "align_result": align_result,
        "display_entity_df": pd.DataFrame(display_entities),
        "entity_df": entity_df,
        "time_df": time_df,
        "masked_audio_path": out_path,
    }



idx = 100

result = align_mask_and_show_pii_from_df_index(
    idx=idx,
    df=df,                 # or df
    final_col="final_transcript.1",
    gliner_threshold=0.35,
    piiranha_threshold=0.45,
    show_label=True,
    mask_mode="beep",
)

idx = 134

result = align_mask_and_show_pii_from_df_index(
    idx=idx,
    df=df,                 # or df
    final_col="final_transcript.1",
    gliner_threshold=0.35,
    piiranha_threshold=0.45,
    show_label=True,
    mask_mode="beep",
)

idx = 344

result = align_mask_and_show_pii_from_df_index(
    idx=idx,
    df=df,                 # or df
    final_col="final_transcript.1",
    gliner_threshold=0.35,
    piiranha_threshold=0.45,
    show_label=True,
    mask_mode="beep",
)

idx = 200

result = align_mask_and_show_pii_from_df_index(
    idx=idx,
    df=df,
    final_col="final_transcript.1",
    gliner_threshold=0.35,
    piiranha_threshold=0.45,
    show_label=True,
    mask_mode="beep",
)

idx = 230

result = align_mask_and_show_pii_from_df_index(
    idx=idx,
    df=df,                 # or df
    final_col="final_transcript.1",
    gliner_threshold=0.35,
    piiranha_threshold=0.45,
    show_label=True,
    mask_mode="beep",         # we can use silence or "beep"
)

idx = 232

result = align_mask_and_show_pii_from_df_index(
    idx=idx,
    df=df,                 # or df
    final_col="final_transcript.1",
    gliner_threshold=0.35,
    piiranha_threshold=0.45,
    show_label=True,
    mask_mode="beep",         # we can use silence or "beep"
)

idx = 286

result = align_mask_and_show_pii_from_df_index(
    idx=idx,
    df=df,                 # or df
    final_col="final_transcript.1",
    gliner_threshold=0.35,
    piiranha_threshold=0.45,
    show_label=True,
    mask_mode="beep",         # we can use silence or "beep"
)

import soundfile as sf
import numpy as np
from IPython.display import Audio, display

def play_audio_segment(audio_path, start_time, end_time):
    """
    audio_path: path to wav/audio file
    start_time, end_time: seconds
    """
    audio, sr = sf.read(audio_path, always_2d=False)

    start_time = float(start_time)
    end_time = float(end_time)

    if start_time < 0:
        start_time = 0.0
    if end_time <= start_time:
        raise ValueError("end_time must be greater than start_time")

    start_sample = int(start_time * sr)
    end_sample = int(end_time * sr)

    if start_sample >= len(audio):
        raise ValueError("start_time is beyond audio length")

    end_sample = min(end_sample, len(audio))
    segment = audio[start_sample:end_sample]

    print(f"Playing: {start_time:.3f}s to {end_time:.3f}s")
    display(Audio(segment, rate=sr))

play_audio_segment(
    audio_path="masked_audio_outputs/2026_1bc14563-c17f-5396-8b5b-d515d7ed4749_ch0_idx286_masked.wav",
    start_time=688,
    end_time=695
)

def get_idx_from_callid_channel(df, call_id, channel):
    match = df[
        (df["id"].astype(str) == str(call_id)) &
        (df["channel"].astype(str) == str(channel))
    ]

    if match.empty:
        raise ValueError(f"No row found for id={call_id}, channel={channel}")

    if len(match) > 1:
        print("Warning: multiple matches found. Returning the first one.")

    return match.index[0]

idx = get_idx_from_callid_channel(df, call_id="2023_8337dde6-11b8-5a05-befd-066be716b102", channel="ch0")
print(idx)

idx = 354

result = align_mask_and_show_pii_from_df_index(
    idx=idx,
    df=df,                 # or df
    final_col="final_transcript.1",
    gliner_threshold=0.35,
    piiranha_threshold=0.45,
    show_label=True,
    mask_mode="beep",         # we can use silence or "beep"
)

play_audio_segment(
    audio_path="masked_audio_outputs/2024_fc2fa0b8-6a98-54ea-a4d0-07559969d063_ch1_idx354_masked.wav",
    start_time=320,
    end_time=329
)

df.columns

